package AoC;

import java.util.HashSet;
import java.util.Set;

public class SIX {
    public static void main(String[] args) {
        int ammount = 0;
        String[] groups = input.split("\n\n");
        for (int i = 0; i < groups.length; i++) {
            String[] people = groups[i].split("\n");
            Set<Character> set = null;
            for (int j = 0; j < people.length; j++) {
                Set<Character> set1 = new HashSet<>();
                for (int k = 0; k < people[j].length(); k++) {
                    set1.add(people[j].charAt(k));
                }
                if (set == null) set = set1;
                else set.retainAll(set1);
            }
            //System.out.println(set);
            ammount += set.size();
        }
        System.out.println(ammount);
    }

    public static String input = "gyrf\n" +
            "idg\n" +
            "\n" +
            "azedybkmuwgotq\n" +
            "uqztdwasygmb\n" +
            "\n" +
            "ljivrzewb\n" +
            "srndxmz\n" +
            "rzbhtge\n" +
            "rzgl\n" +
            "\n" +
            "zgxbwupetnlrqhjkc\n" +
            "itbfpruxhkcwzlnoeq\n" +
            "xtrlnkpczewuqhb\n" +
            "nxpczrkhulstqweb\n" +
            "\n" +
            "firzbpnk\n" +
            "nfkiz\n" +
            "nfzik\n" +
            "ifkzn\n" +
            "ofkinz\n" +
            "\n" +
            "wjcnrhaixfkpqsveby\n" +
            "pxivekfanqbyhjcwsr\n" +
            "newisvxabphcjkqyrf\n" +
            "\n" +
            "pugwelohkyjfbcviq\n" +
            "phnjxlweqzfocmyuig\n" +
            "cfgqpeuryhiojwl\n" +
            "\n" +
            "bkdnxmyalw\n" +
            "xabwnydk\n" +
            "xynzthwobdk\n" +
            "qedbynukjxwsc\n" +
            "ydbnkwx\n" +
            "\n" +
            "viswnyoqkbte\n" +
            "sbywenoiqktr\n" +
            "qsyebntoikw\n" +
            "yneipakwqbsotr\n" +
            "\n" +
            "hjrt\n" +
            "veypxkabt\n" +
            "ltgjrd\n" +
            "ntg\n" +
            "qctshgz\n" +
            "\n" +
            "bvdlhjsm\n" +
            "lomjbsv\n" +
            "bqjymlvws\n" +
            "bdmjlvsh\n" +
            "\n" +
            "a\n" +
            "tav\n" +
            "\n" +
            "bcvxtesfuinmjh\n" +
            "rmpiezdybo\n" +
            "kebim\n" +
            "\n" +
            "rvh\n" +
            "oj\n" +
            "\n" +
            "iph\n" +
            "wehu\n" +
            "chvux\n" +
            "hzlqy\n" +
            "hcw\n" +
            "\n" +
            "wpgyzinvcqfjd\n" +
            "cgfniboaud\n" +
            "nshdgfimc\n" +
            "gvdtnfclei\n" +
            "\n" +
            "msvpr\n" +
            "vsprim\n" +
            "vmrps\n" +
            "vpsrm\n" +
            "\n" +
            "o\n" +
            "l\n" +
            "o\n" +
            "ank\n" +
            "\n" +
            "gh\n" +
            "hqg\n" +
            "jrwelgh\n" +
            "\n" +
            "mkjfneaytbdulo\n" +
            "voyjhiwgxmza\n" +
            "\n" +
            "hskoajyebxt\n" +
            "scetgvkxohabi\n" +
            "sahotkuexbm\n" +
            "wkrqdsbheaxof\n" +
            "\n" +
            "t\n" +
            "d\n" +
            "thd\n" +
            "h\n" +
            "n\n" +
            "\n" +
            "rqavp\n" +
            "voqcarp\n" +
            "rqavp\n" +
            "\n" +
            "ctujizgpdfsyhvlonqxme\n" +
            "msgctnxpzuojvhefldqiy\n" +
            "gmatoyjevuzcnihpfqxdsl\n" +
            "\n" +
            "mdtzufi\n" +
            "ygcsnupqvmlob\n" +
            "mkwuz\n" +
            "uhaxme\n" +
            "\n" +
            "ytzxmadrlqg\n" +
            "mystocdxlraj\n" +
            "\n" +
            "aqtvywkx\n" +
            "ktqnarmiwv\n" +
            "vkqtwa\n" +
            "\n" +
            "nhrxoaulqywedpvc\n" +
            "yopvrqlxwuhfncda\n" +
            "mqdhxyarpvocluinw\n" +
            "uxsatqrlcwnhvpdyo\n" +
            "\n" +
            "enjrodpvqlmwbtxc\n" +
            "pbxvjtowcldenhmq\n" +
            "dmkcqpnvebwjtxul\n" +
            "\n" +
            "lvfmin\n" +
            "mlni\n" +
            "ojmntsil\n" +
            "nmil\n" +
            "nmli\n" +
            "\n" +
            "subvoexkqcyftwpnhgji\n" +
            "jkoubfrxvwseqcghpyint\n" +
            "ejycpgokbnxfiqvhwust\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "sifjmrtdxgwlqu\n" +
            "gbthemlwpqjr\n" +
            "lavotqynkjzwgrc\n" +
            "\n" +
            "prfwzlsbqo\n" +
            "prlzqsfoib\n" +
            "hjyztflbersqp\n" +
            "\n" +
            "bk\n" +
            "kfm\n" +
            "k\n" +
            "mk\n" +
            "\n" +
            "aucwhbfk\n" +
            "facbhiwujky\n" +
            "fkwdayuehcb\n" +
            "wvkrtfbmuc\n" +
            "\n" +
            "gyzumbvnpwhocqj\n" +
            "jbqtavyizfulmch\n" +
            "\n" +
            "pagjkcvmxyhitubldeqzofsr\n" +
            "sxyjeikqhabvmfozpl\n" +
            "\n" +
            "yqthxfdklpb\n" +
            "kyvqpxfhldt\n" +
            "hkldpxftyq\n" +
            "lhpdtxykfq\n" +
            "ldngypfthkqx\n" +
            "\n" +
            "ryfnmplsoqxj\n" +
            "gmjysxpotqlfnr\n" +
            "syflmroqnjpx\n" +
            "snqpymljxfor\n" +
            "boyjxudlampqvzifrskne\n" +
            "\n" +
            "lfmtwhpaqjedkixsur\n" +
            "osinhqvyuzmrkdepcjl\n" +
            "\n" +
            "ct\n" +
            "htcj\n" +
            "tc\n" +
            "tc\n" +
            "\n" +
            "fzhuqmglpjbae\n" +
            "agwkycslhxvnt\n" +
            "hkaglrsy\n" +
            "\n" +
            "uovdmec\n" +
            "kmdyvjuaso\n" +
            "giprfomqvhbz\n" +
            "\n" +
            "qelmntuoyxwvr\n" +
            "uxyilnwevtko\n" +
            "wtoyxlnuvfae\n" +
            "nlyewokxtquv\n" +
            "\n" +
            "qhxsmyrgap\n" +
            "xyahmqzbsor\n" +
            "eqryxsham\n" +
            "rmshuxqay\n" +
            "\n" +
            "lcqxhsotrbnekzpdaiugwy\n" +
            "alexgbdqscnoipkuzwthyr\n" +
            "pnrehculbkqfsotwzyaxgid\n" +
            "niwodsepgthaklubrzyxcq\n" +
            "\n" +
            "qwpcmxglbszaf\n" +
            "bpgzqawlmfs\n" +
            "rqzfscbmpxlawg\n" +
            "zpsdqfgmlwtab\n" +
            "\n" +
            "rvidmhoykf\n" +
            "fyozsivrqweakxm\n" +
            "jmyirokvfcbu\n" +
            "\n" +
            "guoqxbysa\n" +
            "ohmgeswxbnp\n" +
            "\n" +
            "hevxarygqsfpji\n" +
            "fvherjxsgiqa\n" +
            "hwgfvsijxarq\n" +
            "\n" +
            "adjctfpmziw\n" +
            "uchramiqfjbgtsol\n" +
            "\n" +
            "nzfalgyoqpsxhbwiketjcvd\n" +
            "djztpoyqmwnarcbvuhlikxsefg\n" +
            "\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "\n" +
            "eustpacrgnqil\n" +
            "pbjnurlathgqez\n" +
            "lanureqptg\n" +
            "tpgalqkenur\n" +
            "\n" +
            "gbmftykqpezwadjs\n" +
            "yjvzpeubdfih\n" +
            "\n" +
            "jgbfsdrwuqpci\n" +
            "siwcfurdpbjgq\n" +
            "fcqdwjgubirps\n" +
            "bwsgqjrcpiduf\n" +
            "fwrcgjdspibuq\n" +
            "\n" +
            "atoeqpgf\n" +
            "algdpqstf\n" +
            "nhycpfavutqg\n" +
            "qmtaxflpg\n" +
            "kaftigpjqz\n" +
            "\n" +
            "rmsnuyx\n" +
            "ysumr\n" +
            "clmyrfus\n" +
            "cfrnymus\n" +
            "ivsqujkrmgy\n" +
            "\n" +
            "qhoumzdneyifv\n" +
            "sinrhyezumdvfxoq\n" +
            "dfziomhuyqvelgjn\n" +
            "taymuqhkiowzdnfebvp\n" +
            "cehivoqzdyfmnu\n" +
            "\n" +
            "ktnidhjoyfxq\n" +
            "bqsefxcavg\n" +
            "\n" +
            "wcxhqvf\n" +
            "hvcxwfq\n" +
            "cbvrqxwf\n" +
            "\n" +
            "qs\n" +
            "sq\n" +
            "\n" +
            "oujialgb\n" +
            "iuaolgdj\n" +
            "puldjaigo\n" +
            "\n" +
            "aptesvmx\n" +
            "vesmtap\n" +
            "epvtajfqcsm\n" +
            "vtpaesm\n" +
            "yasbuvtmpe\n" +
            "\n" +
            "netgdzuar\n" +
            "rtugznade\n" +
            "zroaeutndg\n" +
            "dartguenz\n" +
            "dtanrzeug\n" +
            "\n" +
            "tcpbzsroklefnqgum\n" +
            "fvpskqwxzhamyelgdi\n" +
            "\n" +
            "xyzidvwmlc\n" +
            "wmtxvlcqiyzd\n" +
            "dizymwxclv\n" +
            "iwmvdxlczy\n" +
            "\n" +
            "zpuxgdibk\n" +
            "xdygzkibu\n" +
            "dzbgwikxu\n" +
            "zgudikbx\n" +
            "\n" +
            "jqvakogwsfym\n" +
            "pmyaosewq\n" +
            "\n" +
            "zqsjnximufb\n" +
            "ifndjbqmsz\n" +
            "bjflmznksiq\n" +
            "qjnzibdfmsyk\n" +
            "\n" +
            "rotjnygizlfcbuskewvh\n" +
            "sauojklbqnxdwezrv\n" +
            "\n" +
            "cytfdombvhxr\n" +
            "iygebrcfhun\n" +
            "qjcbfrhyw\n" +
            "cylfdkbashr\n" +
            "\n" +
            "fd\n" +
            "d\n" +
            "d\n" +
            "wd\n" +
            "deg\n" +
            "\n" +
            "pvbgnqyaukxzshwf\n" +
            "sjfixcywdq\n" +
            "\n" +
            "uqjhovpxrdsbl\n" +
            "guyxokvzitwldrb\n" +
            "fbnavuoxprdel\n" +
            "\n" +
            "snobf\n" +
            "bfn\n" +
            "fbn\n" +
            "iefbn\n" +
            "\n" +
            "jlaknf\n" +
            "knajgflt\n" +
            "nkfljao\n" +
            "aonkjfl\n" +
            "\n" +
            "ixgzmondtcylfwrjkqph\n" +
            "tfjynhxzoimkgcpqdrwl\n" +
            "qizgtmowkcyjrdxlpnfh\n" +
            "nmzdcfwjlkpxqgithroy\n" +
            "xnjtghpwolqmdyczfikr\n" +
            "\n" +
            "mtnforek\n" +
            "noktrmef\n" +
            "\n" +
            "rcjlpzk\n" +
            "mrlwk\n" +
            "klyrw\n" +
            "\n" +
            "bfxpulovhwrg\n" +
            "eolghwyab\n" +
            "ewhzgolmbn\n" +
            "wdelgtmobh\n" +
            "\n" +
            "tlkn\n" +
            "qnrom\n" +
            "\n" +
            "zdvqybjhsnpwexrtu\n" +
            "ebyjtnhszdlwxvu\n" +
            "\n" +
            "dez\n" +
            "tedjz\n" +
            "ezdfxq\n" +
            "zdmne\n" +
            "\n" +
            "f\n" +
            "fq\n" +
            "cetd\n" +
            "x\n" +
            "\n" +
            "ourfng\n" +
            "wifanuoprg\n" +
            "\n" +
            "uebp\n" +
            "gnkbt\n" +
            "btyi\n" +
            "bkjv\n" +
            "bdsfhczqalmr\n" +
            "\n" +
            "pty\n" +
            "wb\n" +
            "\n" +
            "nlmakqredxhuos\n" +
            "qnuetlhmoxadkrs\n" +
            "lnmasqhudeorxk\n" +
            "\n" +
            "ukplmtfqh\n" +
            "hukqmtlif\n" +
            "\n" +
            "roydfcupmqi\n" +
            "nyqlihwjecarmp\n" +
            "qpmifzsrbkvtxcgy\n" +
            "qxrvyicmp\n" +
            "\n" +
            "woudxiya\n" +
            "dxiauywo\n" +
            "wdxayvoubmi\n" +
            "yaxduwio\n" +
            "\n" +
            "vbqeg\n" +
            "g\n" +
            "gz\n" +
            "\n" +
            "ihlr\n" +
            "blmj\n" +
            "bml\n" +
            "\n" +
            "foxpl\n" +
            "lxpoyt\n" +
            "toplx\n" +
            "\n" +
            "ivfu\n" +
            "iuf\n" +
            "bfiuk\n" +
            "qaofiue\n" +
            "\n" +
            "zxpqvifbng\n" +
            "zqbfgrix\n" +
            "qjbixzfg\n" +
            "fbxgzkuiqw\n" +
            "fiqbxgz\n" +
            "\n" +
            "smo\n" +
            "mos\n" +
            "mos\n" +
            "som\n" +
            "\n" +
            "xikr\n" +
            "ghoxidyfjrv\n" +
            "xri\n" +
            "\n" +
            "mwuntvkiqdlzyrhfcpegjba\n" +
            "lvnqzakutrhgibyepcmwdjf\n" +
            "cpqfhkrizlejbgxywutmavnd\n" +
            "jhrzvkgwynlcipqdbeftaum\n" +
            "\n" +
            "epdgwb\n" +
            "bwgepd\n" +
            "wepbdg\n" +
            "\n" +
            "cygzbmivfakohlpseduqwjxnr\n" +
            "cglvwmukednaijspbqofxrzh\n" +
            "\n" +
            "bcauqehkxdlgymrinzpso\n" +
            "sfdepcalnjyxthumqbz\n" +
            "ezctdnshwpxylqabumv\n" +
            "\n" +
            "ndwbpojtqrcmysxl\n" +
            "kfryzcaxosptjlbdmi\n" +
            "thldpuxcvobyjremsg\n" +
            "\n" +
            "xydhuom\n" +
            "ydehxu\n" +
            "hzudyx\n" +
            "\n" +
            "ahkiuxjcd\n" +
            "akjhqcud\n" +
            "\n" +
            "jksu\n" +
            "rj\n" +
            "jr\n" +
            "jr\n" +
            "\n" +
            "fkdr\n" +
            "frdk\n" +
            "rdkf\n" +
            "rfdk\n" +
            "\n" +
            "ovqesapgbx\n" +
            "exaspgvq\n" +
            "\n" +
            "uihatdx\n" +
            "uieaxht\n" +
            "zthuxia\n" +
            "xtaiuh\n" +
            "\n" +
            "ymvwokanzjlqcdfxhipbteu\n" +
            "yjvehfitownxbdklgqaums\n" +
            "\n" +
            "rx\n" +
            "rx\n" +
            "rx\n" +
            "\n" +
            "qalk\n" +
            "blst\n" +
            "gjwcxly\n" +
            "peizdfnulh\n" +
            "\n" +
            "lbsiouyrfwjvamknpc\n" +
            "zqexdu\n" +
            "\n" +
            "houmwlgtzp\n" +
            "gupwztoml\n" +
            "muowjlzpgt\n" +
            "tmpwlgzuoj\n" +
            "\n" +
            "gjixlvut\n" +
            "kigmvzthdaeybs\n" +
            "tijgvlwcp\n" +
            "givotp\n" +
            "\n" +
            "tfbaz\n" +
            "zbtaf\n" +
            "izqgbaft\n" +
            "\n" +
            "tlmwrsgduvbjza\n" +
            "adsfukryintb\n" +
            "\n" +
            "upgjwafysmv\n" +
            "oeixnbltkd\n" +
            "fuhawvc\n" +
            "\n" +
            "uaqshoxiypcdj\n" +
            "tjrlmgwufbay\n" +
            "vatuyejgm\n" +
            "\n" +
            "swexo\n" +
            "mxewl\n" +
            "lwxepa\n" +
            "duwzjkxengyf\n" +
            "xamqhew\n" +
            "\n" +
            "rtapbujkqowmei\n" +
            "krqwaplejtumi\n" +
            "utdijkaqmhnperw\n" +
            "\n" +
            "wcnhsfzkmyeqilupdb\n" +
            "ukcrnbiwxghyzspedlm\n" +
            "epshdunmvryzclkbwi\n" +
            "\n" +
            "zcelytf\n" +
            "ezyt\n" +
            "\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "ozvib\n" +
            "i\n" +
            "\n" +
            "uwbmlkixdhercgnqoyaz\n" +
            "wxrkglobenicmayqhz\n" +
            "rcyexhnzqwoikmlagb\n" +
            "xcbklqorghwznmiaye\n" +
            "\n" +
            "ve\n" +
            "dvsr\n" +
            "\n" +
            "ksupnltcxwdbh\n" +
            "okcwxlnsu\n" +
            "lcexnswku\n" +
            "nclwsxkru\n" +
            "\n" +
            "dak\n" +
            "akd\n" +
            "\n" +
            "fcgijylwr\n" +
            "jgufmeh\n" +
            "\n" +
            "ulyizsoarvkwceptjbmhgfdxqn\n" +
            "izyeoagpnwcxmjfutbvrslkdhq\n" +
            "htencgbpfirdxjzmksyvawloqu\n" +
            "\n" +
            "ebustwzyiqf\n" +
            "rpb\n" +
            "aglbo\n" +
            "bho\n" +
            "b\n" +
            "\n" +
            "brz\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "kvnrgy\n" +
            "vknry\n" +
            "kydvn\n" +
            "gvknqy\n" +
            "vkny\n" +
            "\n" +
            "tb\n" +
            "tp\n" +
            "bt\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "oifnqlty\n" +
            "ugadmrpchszwvkb\n" +
            "\n" +
            "vodrhnaxcqspkt\n" +
            "vdrpnxtshqkoa\n" +
            "npsdrxtvkohqa\n" +
            "hqoptrvnaksdx\n" +
            "\n" +
            "b\n" +
            "a\n" +
            "\n" +
            "itehmbpogkr\n" +
            "tegrakbohpim\n" +
            "khopmeitgbr\n" +
            "kmgephibrot\n" +
            "bhmgopekrti\n" +
            "\n" +
            "pghymvlrtfesnobzdcuw\n" +
            "azmrsflwbthopenducyv\n" +
            "mhoebpzjwulvqnfxksditrcy\n" +
            "\n" +
            "em\n" +
            "me\n" +
            "epm\n" +
            "me\n" +
            "me\n" +
            "\n" +
            "nalmbtedjx\n" +
            "blckxmte\n" +
            "xbtdle\n" +
            "fygisrxtebl\n" +
            "\n" +
            "wmhbjpgkteq\n" +
            "djxmkvqzenfubs\n" +
            "\n" +
            "f\n" +
            "f\n" +
            "f\n" +
            "\n" +
            "pkotmenbq\n" +
            "yjlasx\n" +
            "rdwfuhzvgci\n" +
            "\n" +
            "dltrozycqhpmvae\n" +
            "coaemlyvhqrdt\n" +
            "eolaqyctmdhrv\n" +
            "lhmocfyetqardv\n" +
            "hcermsdqvlayot\n" +
            "\n" +
            "hktqw\n" +
            "qv\n" +
            "\n" +
            "ewjsvzopmadq\n" +
            "zvtnaqlyorshced\n" +
            "\n" +
            "wqxf\n" +
            "tfq\n" +
            "qwimfu\n" +
            "\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "ix\n" +
            "y\n" +
            "e\n" +
            "\n" +
            "kqgdhpw\n" +
            "gphwjv\n" +
            "\n" +
            "frmujkclp\n" +
            "fpjgscklmbur\n" +
            "kupcjrflm\n" +
            "ipclfrkmejdun\n" +
            "\n" +
            "sjurlncf\n" +
            "nfcjursl\n" +
            "lnrsfucj\n" +
            "rsnflcju\n" +
            "\n" +
            "jzgsw\n" +
            "jzsgw\n" +
            "zwjsg\n" +
            "\n" +
            "stngerzp\n" +
            "etksprnz\n" +
            "espzrktn\n" +
            "dnsrptczyfe\n" +
            "srwpnetz\n" +
            "\n" +
            "hgijsyp\n" +
            "rnejlfqkzvmo\n" +
            "gjx\n" +
            "pjbi\n" +
            "\n" +
            "euwdxcyrt\n" +
            "yurxsdegwcit\n" +
            "wcxderyut\n" +
            "\n" +
            "eih\n" +
            "lnay\n" +
            "pizgbf\n" +
            "dbe\n" +
            "\n" +
            "eiuhd\n" +
            "diu\n" +
            "iyvud\n" +
            "ihund\n" +
            "udine\n" +
            "\n" +
            "sodwj\n" +
            "puzaeyv\n" +
            "\n" +
            "dz\n" +
            "zdk\n" +
            "zd\n" +
            "\n" +
            "hqacbisnmruxwftjdl\n" +
            "fqkribanucldwjhmxst\n" +
            "jifwxubrcmldntashq\n" +
            "cwdsqmhfbiultxnarj\n" +
            "\n" +
            "aufcgbyptlrevdoqxihw\n" +
            "jpciweqanyhtxogldmb\n" +
            "\n" +
            "pxwb\n" +
            "xbwp\n" +
            "pwb\n" +
            "wpb\n" +
            "bpwfs\n" +
            "\n" +
            "oedzvbgfwmy\n" +
            "oygzxmkef\n" +
            "ymzgirojfe\n" +
            "oegsfmlyz\n" +
            "zgeoyfsm\n" +
            "\n" +
            "jiasrghwoycnl\n" +
            "olenjrhycgsaqwi\n" +
            "whsrjcnagyoli\n" +
            "owrhsangjluicyk\n" +
            "lwmshncjdyraogi\n" +
            "\n" +
            "vlu\n" +
            "vxu\n" +
            "vu\n" +
            "\n" +
            "dsxhqcbzyvogrti\n" +
            "qbxduvoycszhgirtl\n" +
            "dbityavcqsgrohfpm\n" +
            "\n" +
            "hopzmudb\n" +
            "mhpza\n" +
            "mphnxzjt\n" +
            "aspghzml\n" +
            "\n" +
            "agesxpnitmfu\n" +
            "sinmgepaukftx\n" +
            "xnfgluespamt\n" +
            "\n" +
            "ui\n" +
            "ui\n" +
            "ui\n" +
            "ui\n" +
            "ui\n" +
            "\n" +
            "jhnitvpbofgrzwux\n" +
            "mdkzvpesowglrjybnx\n" +
            "\n" +
            "manj\n" +
            "janmr\n" +
            "\n" +
            "gmnyvucx\n" +
            "bpdaxosnr\n" +
            "\n" +
            "gaiscflkwb\n" +
            "gaicsflkbdw\n" +
            "sgiacehfwtnklr\n" +
            "kzjaxilsgfwocv\n" +
            "\n" +
            "g\n" +
            "p\n" +
            "m\n" +
            "\n" +
            "prhlofsgdqnmkyjzxebct\n" +
            "mdrgikvyfsehcjbpzoq\n" +
            "yzeusqijhfbgaorcdpwkm\n" +
            "zhdcoqrskameypbgjf\n" +
            "qfyhrpgkozjsmdbce\n" +
            "\n" +
            "zwpt\n" +
            "mgfzhitw\n" +
            "lqbtjkzv\n" +
            "hzyet\n" +
            "\n" +
            "svcz\n" +
            "zvsc\n" +
            "zvsc\n" +
            "svcez\n" +
            "vazsc\n" +
            "\n" +
            "gvqnwbshut\n" +
            "swtgnvbhqu\n" +
            "vguqshbtwn\n" +
            "nrhvtqsubgw\n" +
            "syhlnqvtgwbu\n" +
            "\n" +
            "iflmebyvarw\n" +
            "jzkxdiruyhbvtcgln\n" +
            "\n" +
            "pyxrqtckjmnebwi\n" +
            "wtexcmrykqbhz\n" +
            "\n" +
            "bsvnzucfrk\n" +
            "knszwm\n" +
            "ynjpheqztkio\n" +
            "kznbc\n" +
            "\n" +
            "bu\n" +
            "bur\n" +
            "vub\n" +
            "ub\n" +
            "uvb\n" +
            "\n" +
            "nvkojdfgpq\n" +
            "pqkderhatfnlgmu\n" +
            "kofbnpdqcgx\n" +
            "\n" +
            "xhwersc\n" +
            "lhmyrx\n" +
            "rygxonh\n" +
            "jqhxpfrtdazk\n" +
            "\n" +
            "psxcd\n" +
            "cdqs\n" +
            "hqdsc\n" +
            "cqsd\n" +
            "dcs\n" +
            "\n" +
            "djvpifmswcr\n" +
            "ioekyq\n" +
            "\n" +
            "lyntud\n" +
            "zlunsqytd\n" +
            "yclvhjdnta\n" +
            "stydmln\n" +
            "\n" +
            "atuxelgokzmbydjfvic\n" +
            "oxbjvgifctrpkzdaul\n" +
            "uvhckbxlidojgfzta\n" +
            "idvxakjtogcfhzlub\n" +
            "\n" +
            "hmsinyfzljwbqeco\n" +
            "swzlqmfhjyceobin\n" +
            "fweszmlhqynobijc\n" +
            "ohezfbncylwjisqm\n" +
            "fiuqhwcmsjzblnyoe\n" +
            "\n" +
            "aehyn\n" +
            "hnvw\n" +
            "jhnv\n" +
            "hnv\n" +
            "\n" +
            "ow\n" +
            "vlaerpdk\n" +
            "bfgo\n" +
            "\n" +
            "oqud\n" +
            "ojuxd\n" +
            "duao\n" +
            "ugowtdp\n" +
            "udox\n" +
            "\n" +
            "jni\n" +
            "g\n" +
            "yht\n" +
            "r\n" +
            "qnp\n" +
            "\n" +
            "sqfw\n" +
            "fsqw\n" +
            "fwqs\n" +
            "sfqw\n" +
            "\n" +
            "ofparteyjskwhqn\n" +
            "oyprqefwkhnajts\n" +
            "nhorjqtafkepwys\n" +
            "\n" +
            "udofztnq\n" +
            "xtuqrnozf\n" +
            "dqtfunobz\n" +
            "dotqfuznb\n" +
            "\n" +
            "lsic\n" +
            "otlriay\n" +
            "i\n" +
            "azti\n" +
            "ingpekbv\n" +
            "\n" +
            "hgfpqnsdji\n" +
            "krqdpbzs\n" +
            "\n" +
            "dqkfaw\n" +
            "ypvxakiuhjn\n" +
            "wake\n" +
            "amskzfl\n" +
            "calkof\n" +
            "\n" +
            "nxrbkmvjl\n" +
            "ngeqosyfk\n" +
            "\n" +
            "qedbmzvnil\n" +
            "xgsrdyefaokwjct\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "bk\n" +
            "\n" +
            "fmuacvbnekhsj\n" +
            "uchmkbfsejva\n" +
            "iubydmjtkhwefgvas\n" +
            "\n" +
            "zdscwrmubj\n" +
            "zcjrs\n" +
            "csjrhz\n" +
            "srzcj\n" +
            "zrsjtc\n" +
            "\n" +
            "thbcuqdnzmfpkoeai\n" +
            "nocbtkadmfzieqhp\n" +
            "bocktspdyizwjefqahm\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "ho\n" +
            "o\n" +
            "\n" +
            "wfem\n" +
            "efwm\n" +
            "\n" +
            "cmqz\n" +
            "tqmhxw\n" +
            "mq\n" +
            "\n" +
            "qkfoncmvaxyejup\n" +
            "suemvjkncfoya\n" +
            "coedxskjnlvfamyuh\n" +
            "eufazictrknvymjgo\n" +
            "fnocvkuamyej\n" +
            "\n" +
            "qdlarpwu\n" +
            "irxdawhuel\n" +
            "\n" +
            "uchiqmktobedjpw\n" +
            "gcfeyxzs\n" +
            "\n" +
            "jqgszhuick\n" +
            "ikgjhzsqcu\n" +
            "uhsjgzcqki\n" +
            "\n" +
            "oucamrgjh\n" +
            "eagorujc\n" +
            "aorubcgjvl\n" +
            "aucmjrgo\n" +
            "\n" +
            "hylzadntui\n" +
            "hlyeadnkfiujoq\n" +
            "\n" +
            "igqkejpbaz\n" +
            "bvhxcwmfklnotsj\n" +
            "egjpqbuk\n" +
            "\n" +
            "jansopy\n" +
            "pansyjo\n" +
            "psyonja\n" +
            "\n" +
            "lbi\n" +
            "vxb\n" +
            "b\n" +
            "\n" +
            "pzgvlauqwsbdh\n" +
            "wdpvtqszlbuh\n" +
            "\n" +
            "daeptlomkguirxncqv\n" +
            "awfdnvmbuesixkglrpoq\n" +
            "npxuvqdigarokelm\n" +
            "\n" +
            "yz\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "npskgzeh\n" +
            "kzeghsp\n" +
            "zkjgqpche\n" +
            "kzhuepg\n" +
            "zkpegh\n" +
            "\n" +
            "vxpr\n" +
            "pv\n" +
            "avp\n" +
            "zbvpj\n" +
            "prv\n" +
            "\n" +
            "fjkxhemn\n" +
            "zvliyw\n" +
            "pquktmgbr\n" +
            "\n" +
            "sum\n" +
            "su\n" +
            "us\n" +
            "\n" +
            "sdiufxqhcaz\n" +
            "nzxciqsavgot\n" +
            "\n" +
            "rcnyvbthodijekqux\n" +
            "ukaqgdijobetvynch\n" +
            "qcbrejidpohvyktnu\n" +
            "cyqujdtvnbiohekz\n" +
            "mixdwujvsbcnfeyhotkq\n" +
            "\n" +
            "inpwsmbyfuxl\n" +
            "isupxmnfbwl\n" +
            "snwlipxfmbu\n" +
            "\n" +
            "lmsuedxhkzrqj\n" +
            "qerhwjuzckasp\n" +
            "\n" +
            "xzgehoslkf\n" +
            "moxcwfz\n" +
            "iydqjozrpbnuvt\n" +
            "\n" +
            "sig\n" +
            "qisg\n" +
            "igs\n" +
            "sig\n" +
            "\n" +
            "bcqljwpzuyi\n" +
            "wcyzlpqujbi\n" +
            "wbjpuiczlyvq\n" +
            "\n" +
            "shtyjbogacxvdnmi\n" +
            "iktmfcnadjgoyxszh\n" +
            "jihndtosgycxmaw\n" +
            "gytxndwoucijsmah\n" +
            "cgjomnsdayxhti\n" +
            "\n" +
            "qvsabyidcn\n" +
            "xonyialqrs\n" +
            "edcnsyzvqpikwatg\n" +
            "\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "\n" +
            "dzlwtjsnxkgyiahqefbp\n" +
            "ejtygxbhdszknliwpqfa\n" +
            "sxljzkayhiwgpftdenbq\n" +
            "bnxklhtfsgqejzydpawi\n" +
            "wnsbkaielfxtqdhgyzpj\n" +
            "\n" +
            "td\n" +
            "dt\n" +
            "dt\n" +
            "td\n" +
            "\n" +
            "dunlzacjkxfwio\n" +
            "jxoluzghecntfkswvda\n" +
            "dvuonefxrazwlqkcj\n" +
            "\n" +
            "lj\n" +
            "jl\n" +
            "fjl\n" +
            "lj\n" +
            "\n" +
            "jg\n" +
            "gj\n" +
            "jg\n" +
            "gj\n" +
            "jgow\n" +
            "\n" +
            "zytownda\n" +
            "ypidatnz\n" +
            "tdzyna\n" +
            "aztysnd\n" +
            "\n" +
            "sdpu\n" +
            "dups\n" +
            "psduc\n" +
            "\n" +
            "tkrghylamucowf\n" +
            "fkraltcwhoumg\n" +
            "tlkforumgahdcw\n" +
            "ghakclfumortw\n" +
            "ucomwrlgtfkah\n" +
            "\n" +
            "i\n" +
            "ipgq\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "gtodzkynilx\n" +
            "ckdotngyzxil\n" +
            "zgdokyxtinl\n" +
            "gkyxdtloniz\n" +
            "lsodxypizgktn\n" +
            "\n" +
            "fykzoexpqrtm\n" +
            "yqtxprkfmzoeu\n" +
            "rzkqtoyxmpfe\n" +
            "qnxyerkfzotmp\n" +
            "\n" +
            "nbcwzkyrsafopglvtxu\n" +
            "zftblnxauvpgykrocs\n" +
            "vsxbkaotpdzulfmcenrgy\n" +
            "\n" +
            "cbjpqwxesz\n" +
            "kqmwesjbcvxp\n" +
            "ipsdenrqbwjc\n" +
            "\n" +
            "ktjvpuzwi\n" +
            "tikpjvuwz\n" +
            "zutwijkpv\n" +
            "ptikuvzwj\n" +
            "\n" +
            "bszcq\n" +
            "rbqwhc\n" +
            "bqcv\n" +
            "\n" +
            "dxcekavgultzofhwmrib\n" +
            "fdmgxhoynkeczsr\n" +
            "\n" +
            "zxaqerldupyskgbof\n" +
            "nqszfckmupjadebxrovyg\n" +
            "\n" +
            "akyo\n" +
            "oay\n" +
            "kaoyx\n" +
            "robady\n" +
            "\n" +
            "aqmjfzr\n" +
            "fzjrmaq\n" +
            "frzqmaj\n" +
            "\n" +
            "nyiqgcmtolwxkrvfa\n" +
            "ycvifmwxrntazoqke\n" +
            "nmpxicklagfqyrtwov\n" +
            "alcxkiqvofrtwmyn\n" +
            "\n" +
            "dregtlhwosqbncj\n" +
            "qcaitoernpdwl\n" +
            "ocnvtlqwrade\n" +
            "edrwcoqnytal\n" +
            "\n" +
            "qmiozsepbrwdcvut\n" +
            "rocitbuwpmezdsqv\n" +
            "qeirotzpsumcvwdb\n" +
            "pwosuemvizbdqrtc\n" +
            "tpouqmizbknwdevrsc\n" +
            "\n" +
            "cu\n" +
            "c\n" +
            "uc\n" +
            "tc\n" +
            "\n" +
            "isdvalzmowphu\n" +
            "adzlimvsuc\n" +
            "ialdmuszv\n" +
            "mctdziuvls\n" +
            "iydvzsgxkulmj\n" +
            "\n" +
            "gkcqhmnvedru\n" +
            "dmqknbuv\n" +
            "ibkqnudmv\n" +
            "\n" +
            "tbquifjphxgmdy\n" +
            "ypihtfugjxbdqm\n" +
            "mxyuqfigjpdhbt\n" +
            "jmitdhxpzbqfuyg\n" +
            "mdxbtjpfhucgqiy\n" +
            "\n" +
            "ye\n" +
            "ygj\n" +
            "nzbyw\n" +
            "\n" +
            "xzicukfqrbjyvg\n" +
            "qvuxryfibzkcjg\n" +
            "fijkzxyqbvcgur\n" +
            "yikbgrzujfqxcvh\n" +
            "vcgxbfikjqzyru\n" +
            "\n" +
            "pjqmxcrbwlevkz\n" +
            "mhebzwjlkprqxvc\n" +
            "jzmbpwexrlkvqc\n" +
            "kqcvjrpwbzmlxe\n" +
            "\n" +
            "xvntlauipyj\n" +
            "afpylivjnt\n" +
            "yaltivpjn\n" +
            "\n" +
            "iujp\n" +
            "ipu\n" +
            "\n" +
            "rohvzwjmsld\n" +
            "zowlvmrdcx\n" +
            "rdvombliw\n" +
            "wmalydeogrv\n" +
            "dwolvrm\n" +
            "\n" +
            "huzksiva\n" +
            "ihvuzkas\n" +
            "uksiahvzd\n" +
            "fuzlkasptivh\n" +
            "akuhdsviz\n" +
            "\n" +
            "ieszn\n" +
            "ntkezsc\n" +
            "\n" +
            "cwgi\n" +
            "ciwg\n" +
            "gaicw\n" +
            "wicbg\n" +
            "wicg\n" +
            "\n" +
            "w\n" +
            "ywc\n" +
            "w\n" +
            "wv\n" +
            "wdm\n" +
            "\n" +
            "zowsvmjcbn\n" +
            "szvocjbnwmu\n" +
            "siavwjlcmonhd\n" +
            "\n" +
            "lqoyhktfiz\n" +
            "atfyhkqoz\n" +
            "tyfzqhko\n" +
            "zakhyqfote\n" +
            "\n" +
            "vo\n" +
            "g\n" +
            "b\n" +
            "\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "\n" +
            "qvbia\n" +
            "aibq\n" +
            "baiq\n" +
            "aqib\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "cb\n" +
            "\n" +
            "hlksbft\n" +
            "gftlkbhs\n" +
            "bhyftkls\n" +
            "\n" +
            "noljuaqtdzcrp\n" +
            "ucqrzowkyfhtvs\n" +
            "riozcueqft\n" +
            "qzotrhguewc\n" +
            "htxboqcurzk\n" +
            "\n" +
            "npy\n" +
            "qp\n" +
            "jpoh\n" +
            "\n" +
            "waybxjfupm\n" +
            "exfathbpmju\n" +
            "pxgckazbjfsdomluv\n" +
            "\n" +
            "jtxwszgm\n" +
            "hmbdjwg\n" +
            "xsgdwkj\n" +
            "jwg\n" +
            "fqjueywg\n" +
            "\n" +
            "iuzdhnfclyroagtexkvpqm\n" +
            "orcgyaitufkpvzqlmhexdn\n" +
            "lyebcogizhvnmafqukdxpsrt\n" +
            "dfumoalhqytvczgnrxpike\n" +
            "lypuemaqgxdtvfnhkciroz\n" +
            "\n" +
            "hdgtijpbwonlcaum\n" +
            "ahpwjgtuicblxd\n" +
            "prbejhutdgfclwai\n" +
            "\n" +
            "ujskletabhcivfx\n" +
            "vkhlaebujxogqtsc\n" +
            "xsijklvaethfbcu\n" +
            "\n" +
            "sghjfxpmya\n" +
            "xfdumpgjha\n" +
            "\n" +
            "pqmkonlshf\n" +
            "ewlsofidnmcqzyk\n" +
            "lkafmnsxqo\n" +
            "\n" +
            "xjchwm\n" +
            "jomchw\n" +
            "\n" +
            "thelwgdkovnfzmjuyqxcib\n" +
            "jsdfgzmktvlcunbyqoh\n" +
            "nvygolqmtbfzhukdcj\n" +
            "\n" +
            "sle\n" +
            "eliks\n" +
            "lsbq\n" +
            "svle\n" +
            "\n" +
            "hlrsuyotkjmcvbwnqpx\n" +
            "huctkoqvsrnxmwpbjyl\n" +
            "csvmxuhqrwbydgplkijton\n" +
            "\n" +
            "ebfykaztums\n" +
            "zfmekhuyb\n" +
            "ibekzuymfn\n" +
            "vzefckmqybupr\n" +
            "mzeksdyfub\n" +
            "\n" +
            "znqtghesbp\n" +
            "ufrojtmyspqlwcixvk\n" +
            "phtsazdq\n" +
            "\n" +
            "wiafhxgsobktrcvjlmeun\n" +
            "cfsxbnmvhlgwuakojir\n" +
            "nvkbfaomlzcsuhwixjrg\n" +
            "\n" +
            "hujpolkysqdmg\n" +
            "dmkgyhpolujs\n" +
            "dirfmgnkopuwsjhyx\n" +
            "mjkapyshduolg\n" +
            "\n" +
            "elmbxyostpqi\n" +
            "eqopxiyvulmast\n" +
            "lyxosqmetpi\n" +
            "xolsentpyiqm\n" +
            "\n" +
            "e\n" +
            "az\n" +
            "j\n" +
            "j\n" +
            "\n" +
            "bayqmsi\n" +
            "ibsayqm\n" +
            "\n" +
            "bfnclmvtih\n" +
            "ihlvnmcft\n" +
            "vicmfhlnt\n" +
            "cvolkimthfn\n" +
            "cvtlnifmh\n" +
            "\n" +
            "avf\n" +
            "nwbaxy\n" +
            "mplva\n" +
            "la\n" +
            "\n" +
            "egjnmwkqiahrflzts\n" +
            "arluynbwemjizskqhtg\n" +
            "ptmswvldnezaojcxrhkgqi\n" +
            "hglwmtizrknsfjqea\n" +
            "\n" +
            "nbmtjwr\n" +
            "ntswzjc\n" +
            "\n" +
            "tanchrkuoj\n" +
            "ohnujkvtca\n" +
            "naokjcuhtr\n" +
            "\n" +
            "nprvjlhaoygtbwzucf\n" +
            "zslbnuycjwvaoirxfhe\n" +
            "\n" +
            "calgo\n" +
            "zkcvhqlxuyrojgi\n" +
            "cfeldog\n" +
            "waglcdpto\n" +
            "cgltonb\n" +
            "\n" +
            "hpniektlgy\n" +
            "oqiwabgxkry\n" +
            "\n" +
            "conl\n" +
            "dcon\n" +
            "obnc\n" +
            "ncjsoi\n" +
            "conad\n" +
            "\n" +
            "txqd\n" +
            "drtz\n" +
            "dt\n" +
            "dt\n" +
            "\n" +
            "ye\n" +
            "wjey\n" +
            "\n" +
            "cgilao\n" +
            "cagiol\n" +
            "ocliga\n" +
            "\n" +
            "ncbkimptlfvqzgsyoxr\n" +
            "oslrtybmcgpzfqxvin\n" +
            "olqvzbimpxrftcgsyn\n" +
            "yrpzvclsgxfnqibmot\n" +
            "\n" +
            "tdaxubnpsfvjcezyh\n" +
            "rmilkwhgov\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "nykpfic\n" +
            "pvoyc\n" +
            "\n" +
            "bhvpcnq\n" +
            "jvhqbcnp\n" +
            "ncvmpkwqbh\n" +
            "\n" +
            "kjs\n" +
            "kjs\n" +
            "\n" +
            "mux\n" +
            "xum\n" +
            "xomu\n" +
            "mux\n" +
            "\n" +
            "vbaoyigrdhxzuswlnqct\n" +
            "xvsdctrhlunqoyzgabi\n" +
            "qrbtlvfzyjhciaxmsgend\n" +
            "nksbxlgzvdtyihacqr\n" +
            "\n" +
            "mntuey\n" +
            "euntym\n" +
            "myneut\n" +
            "yemnxvtu\n" +
            "ytmunze\n" +
            "\n" +
            "owgzptuxh\n" +
            "zxhtwgu\n" +
            "xcjztuhwg\n" +
            "azgwtxhu\n" +
            "\n" +
            "juz\n" +
            "juzv\n" +
            "juz\n" +
            "juz\n" +
            "\n" +
            "gkdc\n" +
            "dckg\n" +
            "gdkc\n" +
            "cdgk\n" +
            "dgck\n" +
            "\n" +
            "dwmuhygrbklpac\n" +
            "mrwpagyzuldchbk\n" +
            "brmdyolaeckguwxph\n" +
            "asdhfgqkujvrlbpnywmc\n" +
            "cwmdrgyhlbupak\n" +
            "\n" +
            "mnhd\n" +
            "hndm\n" +
            "nmdh\n" +
            "fmnodshv\n" +
            "\n" +
            "p\n" +
            "fpvz\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "gyuecsmv\n" +
            "uvyxh\n" +
            "pburfnj\n" +
            "\n" +
            "tkucsaqn\n" +
            "\n" +
            "v\n" +
            "rv\n" +
            "va\n" +
            "v\n" +
            "v\n" +
            "\n" +
            "nhzvypaqts\n" +
            "wnkodecmfabsi\n" +
            "rxjhtuvqnglayps\n" +
            "\n" +
            "g\n" +
            "r\n" +
            "h\n" +
            "h\n" +
            "r\n" +
            "\n" +
            "ybmx\n" +
            "abym\n" +
            "mb\n" +
            "mbi\n" +
            "ybm\n" +
            "\n" +
            "johvcuezgtsbpxaimqr\n" +
            "ruevbsmjxhpcoqtzlg\n" +
            "\n" +
            "hvysxikeqtdmr\n" +
            "xiyjsk\n" +
            "xbcyaopnuzw\n" +
            "\n" +
            "fapzbkletv\n" +
            "bapftvzlk\n" +
            "lvhpkfatbz\n" +
            "lbfypuzkwamtv\n" +
            "kfbavlztp\n" +
            "\n" +
            "svaqlpxucmzkrfjohi\n" +
            "ivskuacfrmlqzoxhtpj\n" +
            "\n" +
            "knctumya\n" +
            "nctaju\n" +
            "uatjnysbch\n" +
            "tdcxfvnuaeliozwq\n" +
            "\n" +
            "dzytih\n" +
            "dtzyhi\n" +
            "\n" +
            "ngbrdlfsvpcwohyuq\n" +
            "bgoqflawvrycunhspd\n" +
            "gueyqhfprzivmksldbcnowx\n" +
            "lysqfuthbvrwdocnjapg\n" +
            "\n" +
            "guiycvqhbdpzomjwtak\n" +
            "odhmgayvtbuqzwcji\n" +
            "\n" +
            "oq\n" +
            "qgb\n" +
            "pqd\n" +
            "\n" +
            "yqwm\n" +
            "gteo\n" +
            "\n" +
            "ayewhixqouvmgtcb\n" +
            "almuxgfwnqyihtpv\n" +
            "zuvwrxhijmtqy\n" +
            "maxivtqwyhguo\n" +
            "\n" +
            "hltcx\n" +
            "ctlh\n" +
            "tlqhc\n" +
            "htcl\n" +
            "htcdal\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "fn\n" +
            "\n" +
            "wfitcgkp\n" +
            "ipfrswtckg\n" +
            "\n" +
            "iukzpvmdsaeg\n" +
            "svexazbgu\n" +
            "jfvexasqhwzgu\n" +
            "\n" +
            "feghc\n" +
            "gechfr\n" +
            "\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "ynkjbfpd\n" +
            "nfvupjmakbd\n" +
            "fjndkpb\n" +
            "jkfpdbn\n" +
            "\n" +
            "zws\n" +
            "zgws\n" +
            "zsw\n" +
            "\n" +
            "d\n" +
            "d\n" +
            "d\n" +
            "d\n" +
            "d\n" +
            "\n" +
            "z\n" +
            "n\n" +
            "l\n" +
            "h\n" +
            "n\n" +
            "\n" +
            "gjcyeaznrqu\n" +
            "rayqecgnzuj\n" +
            "gzeyuraqnjc\n" +
            "eczayrnujqg\n" +
            "\n" +
            "iocbpjfwlhrxndmsek\n" +
            "owxfhiepmkrlcsjdnb\n" +
            "eshyjbirfpdoaxmvclkw\n" +
            "elbjrougipcwsntmdhfkx\n" +
            "\n" +
            "dkeurwgtqn\n" +
            "rgenwdu\n" +
            "\n" +
            "tfarceyingkbop\n" +
            "lhjvugpnmykoxrbq\n" +
            "knacpbrzygedosw\n" +
            "\n" +
            "kobz\n" +
            "bokn\n" +
            "qflwuebp\n" +
            "\n" +
            "dyqwekiruclshg\n" +
            "cryewliukqgds\n" +
            "iuleqgdcyrksw\n" +
            "\n" +
            "kdvpq\n" +
            "qvyubfad\n" +
            "etbdpqyv\n" +
            "dqcxrghvs\n" +
            "\n" +
            "y\n" +
            "ys\n" +
            "\n" +
            "lyhagitc\n" +
            "fnveaw\n" +
            "\n" +
            "lsfdjyhmoeu\n" +
            "yfejohulmsd\n" +
            "fjlhyeudsom\n" +
            "\n" +
            "mniftya\n" +
            "ijltzbfepsy\n" +
            "itfvkqdy\n" +
            "vifyqt\n" +
            "rtifucy\n" +
            "\n" +
            "aonbkfp\n" +
            "rfkomsd\n" +
            "kofc\n" +
            "osfkvj\n" +
            "\n" +
            "hbdgrpceyl\n" +
            "hcyreldgv\n" +
            "glcdrehvy\n" +
            "rcgekdhyl\n" +
            "\n" +
            "ansgvxpomebrdcl\n" +
            "ovgsrmcdelbxanp\n" +
            "xmdncogrplbvsea\n" +
            "vpawrsgxmenocbdl\n" +
            "\n" +
            "ogyzrvwxqh\n" +
            "yrgzkqwuhx\n" +
            "zgxhwuqkyr\n" +
            "\n" +
            "nbg\n" +
            "gtnbs\n" +
            "\n" +
            "jtnofeiuvlbrmh\n" +
            "zyawocelgk\n" +
            "\n" +
            "b\n" +
            "m\n" +
            "b\n" +
            "b\n" +
            "b\n" +
            "\n" +
            "rwphas\n" +
            "wrpahs\n" +
            "rwspah\n" +
            "pwrhsa\n" +
            "srhawp\n" +
            "\n" +
            "r\n" +
            "r\n" +
            "mre\n" +
            "emr\n" +
            "kngar\n" +
            "\n" +
            "uqjawytvifep\n" +
            "aipuewxlfqjt\n" +
            "\n" +
            "vklrwcjdgpm\n" +
            "cakmpljdvwr\n" +
            "wpjarkvcmd\n" +
            "cdmtrkvwjebp\n" +
            "wkmcpvdjr\n" +
            "\n" +
            "axnklmz\n" +
            "kxaemz\n" +
            "wzdmakb\n" +
            "akmz\n" +
            "\n" +
            "ipfabsdv\n" +
            "pdfixquebh\n" +
            "pdjiomwn\n" +
            "\n" +
            "belkx\n" +
            "xk\n" +
            "xbk\n" +
            "wkox\n" +
            "knx\n" +
            "\n" +
            "ftpdivmrbogczanqyeuwsklxjh\n" +
            "ipzvsrfuaqlkwmyecdbhoxntjg\n" +
            "\n" +
            "vabmipqhewtucyg\n" +
            "qictbweuyamvghp\n" +
            "eahovtgyunrwqbzljcdmi\n" +
            "cigvabemqsyuhwt\n" +
            "vxbmkqcyewaihutg\n" +
            "\n" +
            "rtjencqvhxdiuwkmsgpbl\n" +
            "ghlsxwidjpbveuctrqk\n" +
            "\n" +
            "ykgs\n" +
            "ospkgly\n" +
            "sykg\n" +
            "sgvyexbwqkrj\n" +
            "\n" +
            "puh\n" +
            "cusph\n" +
            "hupg\n" +
            "uph\n" +
            "\n" +
            "wxtlzho\n" +
            "ixvwrkeztyls\n" +
            "lxabwnozt\n" +
            "\n" +
            "jrmycufpowzaiqx\n" +
            "jiypaxfcrqowzum\n" +
            "xqwuyzacoripmfj\n" +
            "yoirjfxqpumcawz\n" +
            "uwqzifxcoryjpam\n" +
            "\n" +
            "zacsuygtenfm\n" +
            "jkoxdhbpru\n" +
            "\n" +
            "pq\n" +
            "qc\n" +
            "\n" +
            "ho\n" +
            "oh\n" +
            "\n" +
            "ijcgvnpyb\n" +
            "gvibtnh\n" +
            "nugihvb\n" +
            "ngtvbi\n" +
            "\n" +
            "fltdqybv\n" +
            "bdtvqfl\n" +
            "\n" +
            "xjfkwshbtyuimzrl\n" +
            "ithlufrmkxzbws\n" +
            "mxrsfkihbzlutw\n" +
            "bicxfmskeuwhgolztrvq\n" +
            "\n" +
            "umy\n" +
            "whrk\n" +
            "\n" +
            "dxrihokctqbsvgafwzyelmup\n" +
            "egrmfldsbikuyovxhapzqct\n" +
            "\n" +
            "g\n" +
            "g\n" +
            "g\n" +
            "t\n" +
            "\n" +
            "pfogweznmdxyvji\n" +
            "siofmpejxuyvd\n" +
            "\n" +
            "whcrlnt\n" +
            "rlwngc\n" +
            "rlincw\n" +
            "frwnlc\n" +
            "rlcwni\n" +
            "\n" +
            "xmoyuwdvcpr\n" +
            "xdvpcurwmyo\n" +
            "upryowcdxmv\n" +
            "vcpmyowdxur\n" +
            "umopxyrdvcw\n" +
            "\n" +
            "qstvuiwdbfajrkhx\n" +
            "ukwxjerhibtafvqsd\n" +
            "\n" +
            "ne\n" +
            "eun\n" +
            "ne\n" +
            "enrhv\n" +
            "\n" +
            "rknzqy\n" +
            "rnqkzy\n" +
            "qryknz\n" +
            "ykzqnr\n" +
            "\n" +
            "agh\n" +
            "gp\n" +
            "\n" +
            "kqiserftgyzcau\n" +
            "fazkcsiurty\n" +
            "arstyikzcuf\n" +
            "\n" +
            "drbvalshq\n" +
            "aqszhbrld\n" +
            "oqjlbescphrdw\n" +
            "hdsblzfrq\n" +
            "stbrgdlvihq\n" +
            "\n" +
            "apdbhlmuykeqnvtojcrziwx\n" +
            "jmnvthlrxqikwczyadpoub\n" +
            "gtfwkuhnocvsayzlbmriqpdxj\n" +
            "mlybauezohqcxinjpwtrkvd\n" +
            "\n" +
            "kwcgmbvda\n" +
            "sedgu\n" +
            "\n" +
            "hatorukz\n" +
            "hotkzrua\n" +
            "otakruzh\n" +
            "atzhkuro\n" +
            "oahzurkt\n" +
            "\n" +
            "wl\n" +
            "wz\n" +
            "\n" +
            "zotecjdsbpaw\n" +
            "vdhowresjckyt\n" +
            "jidwnslgomuftc\n" +
            "\n" +
            "pqdge\n" +
            "tbxnc\n" +
            "ro\n" +
            "\n" +
            "vdgtoj\n" +
            "dgvuklfaepnq\n" +
            "togvds\n" +
            "mvgd\n" +
            "\n" +
            "rsf\n" +
            "fs\n" +
            "fs\n" +
            "fts\n" +
            "\n" +
            "uxonatjihgcdzmeklqf\n" +
            "eatkdufcjgxohiznlms\n" +
            "\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "ytfsuvkjzxbcihaq\n" +
            "hecjifgpqbyvtzsa\n" +
            "tjbiqghslmfaveczyd\n" +
            "\n" +
            "bmwlvri\n" +
            "fcmavwrxl\n" +
            "\n" +
            "zexqgsp\n" +
            "rzbepskaio\n" +
            "epswlz\n" +
            "zspe\n" +
            "uszcenp\n" +
            "\n" +
            "tmhqzfcgbslivdeyowknrp\n" +
            "mlwzqdefyjopusnkcigb\n" +
            "\n" +
            "zlcrxnupqhswyieatfdjgvkb\n" +
            "pnixsjchyluavwfqkbezgtd\n" +
            "gabdktwpqvfsylinuecxjhz\n" +
            "gkblsjiqfhvedcnytaxurwzp\n" +
            "ublwondvshzgciaxepkjytqf\n" +
            "\n" +
            "gcedzrhxkuobalqtim\n" +
            "ruaemtkdzclxbgqho\n" +
            "lheagodbkrxzcqumt\n" +
            "\n" +
            "wpkbszjmaytflgiveqcxr\n" +
            "ewfrtpmigxvjacszdqlkby\n" +
            "fncgsytkxqevzblrmaipwj\n" +
            "zjmtebglwqxcvpysiarkf\n" +
            "\n" +
            "bnmcpaxwkosl\n" +
            "bnypamrkfltxow\n" +
            "\n" +
            "yqnzmcljsop\n" +
            "efakgbrxqcutvd\n" +
            "\n" +
            "uzpwcea\n" +
            "cswelb\n" +
            "\n" +
            "dautmpvqhwfr\n" +
            "qrldhmbcuovfj\n" +
            "\n" +
            "cohmywjnksrxdeli\n" +
            "odcqiupjswrymnkx\n" +
            "jxikhrncyobswlpmdu\n" +
            "skocznixvrwmfyjdta\n" +
            "\n" +
            "tpz\n" +
            "zwmajyv\n" +
            "\n" +
            "je\n" +
            "ej\n" +
            "jep\n" +
            "\n" +
            "qrunyaomvc\n" +
            "amnhrd\n" +
            "wrnamhjfd\n" +
            "knrpjmah\n" +
            "jwmltnra\n" +
            "\n" +
            "hrompbgctsjkdxfvaw\n" +
            "orjfpslvhdieckuybxawtm\n" +
            "vhgamztobdxkwsfcprj\n" +
            "\n" +
            "kqljpzfdtec\n" +
            "hflcptkbsezdjq\n" +
            "trzfevpidcq\n" +
            "\n" +
            "mxesy\n" +
            "y\n" +
            "lvqynah\n" +
            "\n" +
            "lbvg\n" +
            "gblv\n" +
            "bvgl\n" +
            "\n" +
            "ile\n" +
            "iovbl\n" +
            "rktwizpn\n" +
            "ei\n" +
            "\n" +
            "oisu\n" +
            "vsiu\n" +
            "efius\n" +
            "isu\n" +
            "usi\n" +
            "\n" +
            "koesljgpc\n" +
            "pjkocsgel\n" +
            "pecgklsjo\n" +
            "pgselkcjo\n" +
            "\n" +
            "wktezlndury\n" +
            "ymodglktwnru\n" +
            "riuntydkwl\n" +
            "\n" +
            "dcmrauwpt\n" +
            "tikhfbyex\n" +
            "qtoczglnjmvu\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "inwzhfjt\n" +
            "nrzwitgeu\n" +
            "tiwhonz\n" +
            "\n" +
            "bweqycjpahrlxzkd\n" +
            "ydqkahcbwjletxpzn\n" +
            "xwzjaqcdyhepkbl\n" +
            "wsijepoqgbfhxlydvckuza\n" +
            "apwqcyxdjzhelbk\n" +
            "\n" +
            "bjryus\n" +
            "jubsry\n" +
            "uyrbjgs\n" +
            "jusybri\n" +
            "jsyubr\n" +
            "\n" +
            "kwtdph\n" +
            "gzrw\n" +
            "usw\n" +
            "oubw\n" +
            "\n" +
            "vpqithk\n" +
            "pviqtkh\n" +
            "qtvkihp\n" +
            "tvpqhik\n" +
            "ktivphqw\n" +
            "\n" +
            "gu\n" +
            "l\n" +
            "zl\n" +
            "z\n" +
            "\n" +
            "ykmtgcb\n" +
            "dpurenvhwfjsq\n" +
            "ytblazxo\n" +
            "\n" +
            "npiujtsxwyelgar\n" +
            "vdesjgxnyipqzalur\n" +
            "ngxalmshbipyrjfec\n" +
            "\n" +
            "iwxnahblcyfjkusqogt\n" +
            "qpkozlcuwtyrdjhnabge\n" +
            "\n" +
            "zruglboynhdsip\n" +
            "nuvqjlcebpdymtxs\n" +
            "ysubnwdplkf\n" +
            "dyulpsrnab\n" +
            "\n" +
            "uqwxagfzmh\n" +
            "fwmugxhqzv\n" +
            "fzhaquxgmw\n" +
            "fuxshmpqgtkznw\n" +
            "hgzwxfmqu\n" +
            "\n" +
            "vpahuxrdq\n" +
            "yqrdv\n" +
            "\n" +
            "ve\n" +
            "ev\n" +
            "\n" +
            "hilmaspcvnqdukrjwtog\n" +
            "pvruhgdnjkwoatqm\n" +
            "hkdmvpowjauqrngt\n" +
            "bhmaogujpvtnqkwdr\n" +
            "qakwmhgrntjupdvof\n" +
            "\n" +
            "r\n" +
            "r\n" +
            "r\n" +
            "r\n" +
            "\n" +
            "kbfylqr\n" +
            "bjyfqlkr\n" +
            "yfkbqrl\n" +
            "\n" +
            "bhfk\n" +
            "gkw\n" +
            "\n" +
            "uknilvzmdgsftxjbhea\n" +
            "mxudehajfnkqcsztgiv\n" +
            "wsivtumagyxerznkdfhj\n" +
            "tedicskzaxnugjvmhf\n" +
            "\n" +
            "cfjp\n" +
            "pjfc\n" +
            "jcfp\n" +
            "pcfj\n" +
            "pcfj\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "mqcbdapjnzrivlfowkhsxg\n" +
            "fswravokdqzbhmlxicnpj\n" +
            "alofpkxhjvibsczqmnwrd\n" +
            "zqoimsplhnjydwcbxakrfv\n" +
            "\n" +
            "wmrpd\n" +
            "wpqdr\n" +
            "zprdfnxu\n" +
            "rpqdk\n" +
            "\n" +
            "nh\n" +
            "hn\n" +
            "hn\n" +
            "nh\n" +
            "qndh\n" +
            "\n" +
            "pbnkvlt\n" +
            "vplfbx\n" +
            "vlpjbeqys\n" +
            "vlphb\n" +
            "rzvlwpmbi\n" +
            "\n" +
            "rnb\n" +
            "rbn\n" +
            "nbr\n" +
            "brn\n" +
            "\n" +
            "fxkhea\n" +
            "kafhex\n" +
            "abjgehfkx\n" +
            "\n" +
            "eapwslhovimkqdfr\n" +
            "frxpewkqhadvlmois\n" +
            "qdelvaiorkshwpfm\n" +
            "\n" +
            "yewquxpoz\n" +
            "ndgtcqiywfe\n" +
            "xwyqoepu\n" +
            "\n" +
            "hagocylexukrqtjimnfs\n" +
            "fqrzxnjvwmpkdgo\n" +
            "\n" +
            "kowdvbptiseqn\n" +
            "svpqkwxf\n" +
            "aqkpvsmwzul\n" +
            "\n" +
            "wdnztvhjgu\n" +
            "nvzujgwthd\n" +
            "huzjvgdnwt\n" +
            "tjwuzghnivd\n" +
            "\n" +
            "jhbcusfirekwqotvplmyxz\n" +
            "xflehjqtorbpyiuczvskwm\n" +
            "yrjbluvmciostqhxkezfpw\n" +
            "otshirjuxfzmwqekvyblcp\n" +
            "yirkuxfsembpjatqvohcwlz\n" +
            "\n" +
            "obpjmy\n" +
            "opabkjm\n" +
            "jbopm\n" +
            "\n" +
            "qhkinmwyzpdla\n" +
            "idatlkhquywvm\n" +
            "dhgwyamklqcin\n" +
            "\n" +
            "wlta\n" +
            "dmxzs\n" +
            "\n" +
            "d\n" +
            "k\n" +
            "x\n" +
            "d\n" +
            "\n" +
            "szfptnyl\n" +
            "tnczeyf\n" +
            "\n" +
            "tfpkx\n" +
            "aiqush\n" +
            "fbmtw";
}
